### ISSUE TITLE
Active by default not working

### ISSUE THREAD

**Issue by Krato** [danieldiekmeier/vue-slide-up-down#1]
Hi, if you put active true by default is not working.

Thanks

**Comment by danieldiekmeier** [comment]
Ah, yes, you're right.

I just pushed a commit that should fix that: https://github.com/danieldiekmeier/vue-slide-up-down/commit/d797a6f0a475c89a7a4625ff9a1ff34efe3e709f

If it doesn't fix your problem, can you post a JSFiddle or a Codepen example so I can take a look? Thanks!

**Comment by Krato** [comment]
Please change line 52 with:

```
if (this.active) {
```

Thanks and regards!

**Comment by danieldiekmeier** [comment]
Whoops, sorry! Changed it.
