### ISSUE TITLE
Programmatically Readjust Height

### ISSUE THREAD

**Issue by zeshanshani** [danieldiekmeier/vue-slide-up-down#10]
## Behaviour
I'm loading content from an API and most of the times, the plugin does not show full height of the content (see: https://s.zeshanahmed.com/a_210C5475.png).

## Expected Behaviour
A custom method that you can trigger to refresh the height of the slider. Something like:

`this.$refs['slide-up-down'].refreshHeight()`

Thank you in advanced!

**Comment by danieldiekmeier** [comment]
Hey! Thanks for the detailed issue. :)

I think the `layout` method should do what you want: https://github.com/danieldiekmeier/vue-slide-up-down/blob/master/src/slide-up-down.js#L66

(It's not documented, but it's still pretty stable.)

Can you check if it works for you? Thanks!
