### ISSUE TITLE
Please add hooks that is triggered when the transition is done

### ISSUE THREAD

**Issue by AndreasHeintze** [danieldiekmeier/vue-slide-up-down#12]
I would like to run some javascript when the transition is done. Can you please add this?

**Comment by danieldiekmeier** [comment]
This is not a bad idea, but I'm not sure when I'll have the time to implement this.

Until then, you could use a `transitionend` event listener on the container element:

```
mounted () {
  const el = this.$refs.upDownEl.$refs.container
  el.addEventListener('transitionend', () => {
    console.log('transition ended')
  })
},
```

See this CodePen for a full example: https://codepen.io/danieldiekmeier/pen/YapGWq

And this article for more information about the event: https://jonsuh.com/blog/detect-the-end-of-css-animations-and-transitions-with-javascript/

**Comment by AndreasHeintze** [comment]
Yes, I did solve it myself. Do you want me to send you a pull request?

**Comment by danieldiekmeier** [comment]
No, thanks!
