### ISSUE TITLE
Not allowed nested components

### ISSUE THREAD

**Issue by carlospalacin** [danieldiekmeier/vue-slide-up-down#13]
If try create nested components of slide-up-down, the inner component doesn't work.

```
<slide-up-down :active="active01">
    <div>

		Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.

		<slide-up-down :active="active02">
			<div>
				Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
			</div>
		</slide-up-down>
    </div>
</slide-up-down>
```
:-(

**Comment by danieldiekmeier** [comment]
Hey Jose,

sorry, I'm afraid this isn't really in the scope of this module. The goal is to provide a very small implementation of a slide component, but I'm afraid adding support for nested components would need significant work and add a lot of code (Relative to the amount of code that's currently necessary.)

I'm not saying it's a bad idea or a bad use case, just that I'm currently not interested in supporting it. Feel free to copy the actual source code of the module into your project (it's very short) and make necessary adjustments yourself, or maybe even publish it afterwards.

Thanks for understanding!
