### ISSUE TITLE
Error in installation instructions inside Readme.md

### ISSUE THREAD

**Issue by TheMrZZ** [danieldiekmeier/vue-slide-up-down#14]
There is a mistake in the installation instructions in the readme. The readme states:
> ## Installation
> `npm i slide-up-down`

The command is wrong. The actual package name is _vue-slide-up-down_, so the instructions should be:
> ## Installation
> `npm i vue-slide-up-down`

**Comment by danieldiekmeier** [comment]
Oh no, good catch. I changed some documentation for the last release, but it seems like I messed up. Thanks!

**Comment by danieldiekmeier** [comment]
Fixed in 1.4.1! <3
