### ISSUE TITLE
Remove height property after animation

### ISSUE THREAD

**Issue by gerhard-lechner** [danieldiekmeier/vue-slide-up-down#17]
Hi Daniel,

first of all thank you for sharing your awesome script! I'm fairly new to VueJS so it helped me out a lot when trying to find a decent show/hide solution (like slideUp() / slideDown() in jQuery).

There is one little issue that bugged me with the current script though: After the transition of an element the height property stays on the div. That will potentially cause problems if the content of the div changes and calling the layout() method felt a bit cumbersome to me.

I tried to fix this and came up with my own solution that only adds the height to the div during the animation and removes it afterwards, just like the jQuery functions do.

I think the way I built it also makes the layout() method obsolete or am I missing something? Any feedback on my approach would be very much appreciated, maybe you could even add a similar behaviour to your script?

Kind regards,
Gerhard

    import Vue from 'vue'

    const showHide = {

      props: {
        opened: {
          type: Boolean,
          default: false
        },
        duration: {
          type: Number,
          default: 500
        },
        tag: {
          type: String,
          default: 'div'
        }
      },

      data: () => ({
        newState: '',
        animationActive: false,
        timeout: false
      }),

      computed: {
        style () {

          // animate to new state
          if (this.newState !== '') {

            // calculate height
            let height = '0px';
            if ((this.newState === 'opened' && this.animationActive === true) ||
                (this.newState === 'closed' && this.animationActive !== true)) {
              height = this.el.scrollHeight + 'px';
            }

            // prepare style params
            const style = {
              height,
              'display': 'block',
              'overflow': 'hidden',
              'transition-property': 'height',
              'transition-duration': this.duration + 'ms'
            }

            // activate animation in 25ms
            // (if the timeout is too short, the browser might skip the animation)
            this.timeout = setTimeout(() => {
              this.animationActive = true
              this.timeout = false
            }, 25)

            return style
          }

          // no new state
          else {
            return { 'display': (this.opened) ? 'block' : 'none' }
          }
        },

        el () {
          return this.$refs.container
        }
      },

      watch: {

        // set newState after opened has been changed
        opened () {
          this.newState = (this.opened) ? 'opened' : 'closed'
          this.animationActive = false
        }
      },

      mounted () {

        // unset newState after transition has ended
        // (only if no timeout is set, otherwise the timed animation will be interrupted)
        this.el.addEventListener('transitionend', () => {
          if (this.timeout === false) {
            this.newState = ''
          }
        })
      },

      render (h) {
        return h(
          this.tag,
          {
            style: this.style,
            ref: 'container'
          },
          this.$slots.default
        )
      }
    }

    Vue.component('show-hide', showHide)

    export default showHide

**Comment by stephan-v** [comment]
Removing the `overflow: hidden` would also be handy since when the animation has completed there is currently no way to have elements stick out of the animated element afterwards.

**Comment by mgurbanzade** [comment]
This is what happens when you delete a comment via ajax and vue-slide-toggle wrapper is opened

<img width="842" alt="screen shot 2018-11-13 at 13 29 49" src="https://user-images.githubusercontent.com/27240114/48403857-4cfb4f80-e748-11e8-8a91-9e015e6135fd.png">

**Comment by bdiz** [comment]
In my case, vue-slide-up-down reveals a textarea which I want to allow to auto grow as the user types. Inside the vue-slide-up-down element the textarea just gets cut off.

Would love to see this fix added.

Thanks.

**Comment by danieldiekmeier** [comment]
Hey @codeworks, thanks for taking the time to post this! I changed the logic a bit (it felt weird to rely on Vue re-computing `style` after the timeout by setting some other variables), but the functionality of your suggestion is now released as `1.5.0`. Thanks!
