### ISSUE TITLE
Recommend not using display none on closed state

### ISSUE THREAD

**Issue by adamhughes86** [danieldiekmeier/vue-slide-up-down#19]
Hey. I noticed in the new version (1.5.0) you've started stripping out the height after transition but you're now adding `display: none` when it's in the closed state. This limits some of the functionality that people can use your plugin for.

In my case I'm expanding from 100px to full height and with the old versions this can be achieved with `min-height`. With 1.5 that approach isn't possible anymore.

> **Min-height example with 1.3.3 - https://codepen.io/lostmybrain/pen/ebJddX**
> **Min-height example with 1.5.0 - https://codepen.io/lostmybrain/pen/xmZELG**

I agree with the premise of removing the open state css after transition but I think the closed state would be better served using:

```
height: 0px;
overflow: hidden;
```

instead of `display: none`

**Comment by danieldiekmeier** [comment]
Yes, you're absolutely right. I just published v1.6 with your suggested fix and min-height should be working again!
