### ISSUE TITLE
Component showing by default when active is set as false

### ISSUE THREAD

**Issue by seth5000** [danieldiekmeier/vue-slide-up-down#20]
Hi,

In version 1.5.0, when active is set as false the component is showing when it is first rendered.

https://codepen.io/anon/pen/yGeWqe

**Comment by bdiz** [comment]
Seeing it too in 1.5.0. In my case my components within vue-slide-up-down are still being loaded when height property is removed. Here's a codepen to demonstrate behavior.

https://codepen.io/bendelsol/pen/PXNaXX

**Comment by danieldiekmeier** [comment]
Yes, thank you! Fixed in v1.6 ❤️
