### ISSUE TITLE
Combine slide-up-down with opacity transition

### ISSUE THREAD

**Issue by sowinski** [danieldiekmeier/vue-slide-up-down#21]
Hi,

how can I include to your animation also a opacity transition?
Please see here an Example:
https://codepen.io/anon/pen/MZjQVx

Thank you :)

**Comment by danieldiekmeier** [comment]
Thanks for the example!

Here is a working fork: https://codepen.io/danieldiekmeier/pen/roMKOo

You have to wrap the `<transition>` around the `<vue-slide-up-down>` component, add a `v-show` attribute, and you need to overwrite the `transition-property`. Another possibility would be to use another wrapper element, like

```
<transition>
  <another-wrapper>
    <vue-slide-up-down />
  </another-wrapper>
</transition>
```

(this doesn't include any attributes, it's just to illustrate what I mean.
