### ISSUE TITLE
Version 1.7.1 Shows element that is hidden by default

### ISSUE THREAD

**Issue by jbrown0824** [danieldiekmeier/vue-slide-up-down#25]
In version 1.7.1 If you attempt to have the :active status false by default, it still shows the element:

https://codepen.io/jbrown0824/pen/pYLKeE

Additionally, there is a javascript error `TypeError: Cannot read property 'active' of undefined`

If I revert to version 1.6.0 it works as expected, and there is no JS error either.

Thanks

**Comment by danieldiekmeier** [comment]
Thank you! I published v1.7.2 which fixes the issue.
