### ISSUE TITLE
Absolute content is not disappearing

### ISSUE THREAD

**Issue by tim-kilian** [danieldiekmeier/vue-slide-up-down#28]
## Problem
I want the same behavior as it is, but with absolute content. In my application there are floating icons if i close the slider.

## Codepen
https://codepen.io/tim-kilian/pen/JQyWJg

**Comment by danieldiekmeier** [comment]
You have to add `position: relative` to the `.element`: https://codepen.io/danieldiekmeier/pen/XLaMVG

This is not a problem with `vue-slide-up-down`, but with the way `overflow: hidden` works with children that have `position: absolute`.
