### ISSUE TITLE
Horizontal sliding support planned?

### ISSUE THREAD

**Issue by denjaland** [danieldiekmeier/vue-slide-up-down#30]
Hi guys,

What a GREAT library this is.  Any plans on adding support for a horizontal slide that we can use to nicely have the left and/or right menu panels slide in/out?

**Comment by danieldiekmeier** [comment]
Hey @denjaland, this is not planned at the moment.

**Comment by fthues** [comment]
Would you be open to a pull request implementing this particular feature?

**Comment by danieldiekmeier** [comment]
Not really, sorry! I like the current simplicity and small size. Also, I haven't used `vue-slide-up-down` in years, so I'd rather avoid adding new features/potential for bugs.
