### ISSUE TITLE
Having transitions inside the slide-up-down content causes the sliding animation to bug out

### ISSUE THREAD

**Issue by tincann** [danieldiekmeier/vue-slide-up-down#33]
Hi there,

Thanks for making this nice plugin. I've noticed the sliding animation was bugging out for some components where I used slide-up-down. Vue devtools also showed that the 'open-end' event was being triggered many times per second when hovering over certain stuff.

It seems that any content inside the slide-up-down component that uses a transition will trigger this event. 

I've isolated the problem in this codepen: https://codepen.io/mortennn/pen/dyPeydK

Things to notice:
- When hovering over the buttons, the 'open-end' event is constantly firing
- When clicking on one of the buttons, the animation immediately ends in the endstate

This problem can probably be fixed by filtering the event target inside the `onTransitionEnd()` function to exclude child elements.

**Comment by danieldiekmeier** [comment]
Hey @tincann, thanks for the great reproduction! It was very easy to fix the problem, and I just released `vue-slide-up-down@2.0.1` with a fix for your error. Thanks!

**Comment by tincann** [comment]
@danieldiekmeier Thanks for the quick fix. Much appreciated!
