### ISSUE TITLE
Custom HTML output tag

### ISSUE THREAD

**Issue by dutchwebworks** [danieldiekmeier/vue-slide-up-down#4]
Great plugin.

Is it possible to determine, for example via Vue bind `:tag`, which tag your plugin uses for output? By default it's always a `div` -tag. But I'd like to change that to a `p` or a `dd` -tag.

For example:
```html
<dl class="faq">
	<dt>My question</dt>

	<vue-slide-up-down
		:tag="dd"
		:active="active"
		:duration="1000">
		The answer. Lorem ipsum etc...
	</vue-slide-up-down>
</dl>
```

The result would be:

```html
<dl class="faq">
	<dt>My question</dt>
	<dd>The answer. Lorem ipsum etc...</dd>
</dl>
```

Of course on a real web page it would have more `dt` and `dd` -tags etc. for a FAQ like expanding setup.

**Comment by danieldiekmeier** [comment]
Very good idea! I just published v1.3.0 which includes this change! Thank you 🎉
