### ISSUE TITLE
Vue 3 Support

### ISSUE THREAD

**Issue by doutatsu** [danieldiekmeier/vue-slide-up-down#44]
This package doesn't work in Vue 3. Could support be added?

**Comment by doutatsu** [comment]
A fork actually exists already, but would be nice to get the main library up to date -> https://github.com/craigrileyuk/vue3-slide-up-down

**Comment by danieldiekmeier** [comment]
Hello! Sorry for being [checks watch] two years late, but I just released v3.0.0 of this library, which does add support for Vue 3! 🎉
