### ISSUE TITLE
Focusable elements

### ISSUE THREAD

**Issue by DwayneHawkins** [danieldiekmeier/vue-slide-up-down#45]
Is there a way to remove the element from the DOM like _v-if_ does? Or maybe at least the equivalent of _v-show_.
More like vuejs does with the default transition component.

The problem with focusable elements makes this (nice) slider component unusable for me right now.

**Comment by danieldiekmeier** [comment]
Sorry for being almost two years late. if you don't remember/care what this is about, I don't clame you. :D 

I'm afraid I don't really understand the problem. When the slider is closed, by default it also gets the `hidden` attribute, making its children non-focusable. Is this not working for you?

**Comment by DwayneHawkins** [comment]
If I remember correctly, the problem is you can still focus input fields etc in the slide wrapper when it is closed, messing up tab sequence when you tab through a form for example. So you end up having focus on an input field you can't see.

**Comment by danieldiekmeier** [comment]
If you look at the Demo: https://codepen.io/danieldiekmeier/pen/YapGWq

There is a container which can be toggled with the "Toggle Content" button. In the container, there is an `<input>` element. By default, when the container is closed, I can't tab to the `<input>` – Only when it's open.

But it's possible to set `:use-hidden="false"`, which does indeed allow me to tab to the input element. But it's not the default, and it's warned against in the Readme.

**Comment by DwayneHawkins** [comment]
Nice. Not really sure about the usecase anymore but I think it had to do with scripts not realizing the input is in a `hidden` container, thus thinking it's still focusable. Propably something to do with a tabtrap script in a popup or dialog ... but it's a looong time ago.
Anyway, thanks for your time and have a good one!
